2015-07-14 09:57:29,785 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb45e50>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 09:57:40,519 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea91290>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 09:57:48,998 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb47e90>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 09:58:01,427 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb47e90>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 10:20:26,189 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ec753d0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:23:03,489 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eaa3290>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:23:13,822 - DEBUG - Checking for viewers in django.contrib.auth.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,829 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,831 - DEBUG - Checking for viewers in django.contrib.contenttypes.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,832 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,834 - DEBUG - Checking for viewers in django.contrib.sessions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,835 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,837 - DEBUG - Checking for viewers in django.contrib.sites.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,838 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,840 - DEBUG - Checking for viewers in django.contrib.flatpages.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,841 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,843 - DEBUG - Checking for viewers in django.contrib.admin.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,844 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,846 - DEBUG - Checking for viewers in django.contrib.humanize.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,847 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,849 - DEBUG - Checking for viewers in django.contrib.comments.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,850 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,852 - DEBUG - Checking for viewers in django.contrib.redirects.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,853 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,855 - DEBUG - Checking for viewers in django_extensions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,856 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,858 - DEBUG - Checking for viewers in google_analytics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,859 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,861 - DEBUG - Checking for viewers in rooibos.data.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,863 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,865 - DEBUG - Checking for viewers in rooibos.migration.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,868 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,871 - DEBUG - Checking for viewers in rooibos.mobile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,874 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,877 - DEBUG - Checking for viewers in rooibos.util.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,879 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,882 - DEBUG - Checking for viewers in rooibos.access.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,885 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,888 - DEBUG - Checking for viewers in rooibos.solr.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,890 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,893 - DEBUG - Checking for viewers in rooibos.storage.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,913 - DEBUG - Successfully registered viewer mediaplayer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,915 - DEBUG - Checking for viewers in rooibos.legacy.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,918 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,921 - DEBUG - Checking for viewers in rooibos.ui.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,923 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,926 - DEBUG - Checking for viewers in rooibos.viewers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,929 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,931 - DEBUG - Checking for viewers in rooibos.help.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,934 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,936 - DEBUG - Checking for viewers in rooibos.presentation.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,964 - DEBUG - Successfully registered viewer presentationviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,965 - DEBUG - Successfully registered viewer flashcardviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,966 - DEBUG - Successfully registered viewer printviewviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,967 - DEBUG - Successfully registered viewer packagefilesviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,968 - DEBUG - Successfully registered viewer htmlpresentation [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:13,969 - DEBUG - Checking for viewers in rooibos.statistics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,970 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,972 - DEBUG - Checking for viewers in rooibos.federatedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,973 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,975 - DEBUG - Checking for viewers in rooibos.unitedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,976 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,978 - DEBUG - Checking for viewers in rooibos.converters.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,979 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,981 - DEBUG - Checking for viewers in rooibos.contrib.tagging.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,982 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,984 - DEBUG - Checking for viewers in rooibos.workers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,985 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,987 - DEBUG - Checking for viewers in rooibos.userprofile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,988 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,990 - DEBUG - Checking for viewers in rooibos.mediaviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:13,991 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:13,993 - DEBUG - Checking for viewers in rooibos.megazine.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,011 - DEBUG - Successfully registered viewer megazine [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:14,012 - DEBUG - Checking for viewers in rooibos.groupmanager.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,014 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:14,015 - DEBUG - Checking for viewers in rooibos.pdfviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,032 - DEBUG - Successfully registered viewer pdfviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:14,033 - DEBUG - Checking for viewers in rooibos.pptexport.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,073 - DEBUG - Successfully registered viewer powerpointexportviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:14,074 - DEBUG - Checking for viewers in rooibos.audiotextsync.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,095 - DEBUG - Successfully registered viewer audiotextsyncviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:14,096 - DEBUG - Checking for viewers in pagination.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,097 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:14,099 - DEBUG - Checking for viewers in impersonate.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,100 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:14,102 - DEBUG - Checking for viewers in compressor.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,103 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:14,105 - DEBUG - Checking for viewers in south.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,106 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:14,108 - DEBUG - Checking for viewers in django_concurrent_test_server.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:14,109 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,641 - DEBUG - Checking for viewers in django.contrib.auth.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,643 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,645 - DEBUG - Checking for viewers in django.contrib.contenttypes.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,646 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,648 - DEBUG - Checking for viewers in django.contrib.sessions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,649 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,651 - DEBUG - Checking for viewers in django.contrib.sites.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,652 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,654 - DEBUG - Checking for viewers in django.contrib.flatpages.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,655 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,657 - DEBUG - Checking for viewers in django.contrib.admin.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,658 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,660 - DEBUG - Checking for viewers in django.contrib.humanize.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,661 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,663 - DEBUG - Checking for viewers in django.contrib.comments.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,664 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,666 - DEBUG - Checking for viewers in django.contrib.redirects.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,667 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,669 - DEBUG - Checking for viewers in django_extensions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,670 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,672 - DEBUG - Checking for viewers in google_analytics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,673 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,675 - DEBUG - Checking for viewers in rooibos.data.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,676 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,678 - DEBUG - Checking for viewers in rooibos.migration.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,679 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,681 - DEBUG - Checking for viewers in rooibos.mobile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,682 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,684 - DEBUG - Checking for viewers in rooibos.util.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,685 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,686 - DEBUG - Checking for viewers in rooibos.access.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,688 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,689 - DEBUG - Checking for viewers in rooibos.solr.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,691 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,692 - DEBUG - Checking for viewers in rooibos.storage.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,696 - DEBUG - Successfully registered viewer mediaplayer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,697 - DEBUG - Checking for viewers in rooibos.legacy.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,698 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,700 - DEBUG - Checking for viewers in rooibos.ui.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,701 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,703 - DEBUG - Checking for viewers in rooibos.viewers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,704 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,706 - DEBUG - Checking for viewers in rooibos.help.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,707 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,709 - DEBUG - Checking for viewers in rooibos.presentation.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,716 - DEBUG - Successfully registered viewer presentationviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,717 - DEBUG - Successfully registered viewer flashcardviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,718 - DEBUG - Successfully registered viewer printviewviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,719 - DEBUG - Successfully registered viewer packagefilesviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,720 - DEBUG - Successfully registered viewer htmlpresentation [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,721 - DEBUG - Checking for viewers in rooibos.statistics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,723 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,724 - DEBUG - Checking for viewers in rooibos.federatedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,726 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,727 - DEBUG - Checking for viewers in rooibos.unitedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,729 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,730 - DEBUG - Checking for viewers in rooibos.converters.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,732 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,733 - DEBUG - Checking for viewers in rooibos.contrib.tagging.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,735 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,736 - DEBUG - Checking for viewers in rooibos.workers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,738 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,739 - DEBUG - Checking for viewers in rooibos.userprofile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,741 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,742 - DEBUG - Checking for viewers in rooibos.mediaviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,744 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,745 - DEBUG - Checking for viewers in rooibos.megazine.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,748 - DEBUG - Successfully registered viewer megazine [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,749 - DEBUG - Checking for viewers in rooibos.groupmanager.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,750 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,752 - DEBUG - Checking for viewers in rooibos.pdfviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,754 - DEBUG - Successfully registered viewer pdfviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,755 - DEBUG - Checking for viewers in rooibos.pptexport.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,758 - DEBUG - Successfully registered viewer powerpointexportviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,759 - DEBUG - Checking for viewers in rooibos.audiotextsync.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,760 - DEBUG - Successfully registered viewer audiotextsyncviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:23:21,761 - DEBUG - Checking for viewers in pagination.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,763 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,764 - DEBUG - Checking for viewers in impersonate.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,766 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,767 - DEBUG - Checking for viewers in compressor.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,769 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,770 - DEBUG - Checking for viewers in south.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,772 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:21,773 - DEBUG - Checking for viewers in django_concurrent_test_server.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:23:21,775 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:23:23,669 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ec54ad0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:23:27,174 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ec76790>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:23:47,756 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:23:47,795 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:23:47,845 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:23:48,446 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:23:49,146 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 750 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:23:49,418 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:23:49,568 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:24:10,288 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ec72f10>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:25:35,617 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb4c390>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:26:18,452 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea4e6d0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:26:31,269 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:26:31,266 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:26:31,274 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:26:31,525 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:26:31,544 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:26:31,945 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:26:32,627 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 752 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:31:25,496 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea8e250>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:32:30,673 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea52690>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:32:42,172 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb45e10>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:33:00,568 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea50690>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:33:05,718 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ebb49d0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:33:08,170 - DEBUG - Checking for viewers in django.contrib.auth.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,172 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,174 - DEBUG - Checking for viewers in django.contrib.contenttypes.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,175 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,177 - DEBUG - Checking for viewers in django.contrib.sessions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,178 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,180 - DEBUG - Checking for viewers in django.contrib.sites.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,181 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,183 - DEBUG - Checking for viewers in django.contrib.flatpages.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,184 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,186 - DEBUG - Checking for viewers in django.contrib.admin.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,187 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,189 - DEBUG - Checking for viewers in django.contrib.humanize.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,190 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,192 - DEBUG - Checking for viewers in django.contrib.comments.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,193 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,195 - DEBUG - Checking for viewers in django.contrib.redirects.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,196 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,198 - DEBUG - Checking for viewers in django_extensions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,199 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,201 - DEBUG - Checking for viewers in google_analytics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,202 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,204 - DEBUG - Checking for viewers in rooibos.data.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,205 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,207 - DEBUG - Checking for viewers in rooibos.migration.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,208 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,210 - DEBUG - Checking for viewers in rooibos.mobile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,211 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,213 - DEBUG - Checking for viewers in rooibos.util.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,214 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,216 - DEBUG - Checking for viewers in rooibos.access.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,217 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,219 - DEBUG - Checking for viewers in rooibos.solr.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,220 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,222 - DEBUG - Checking for viewers in rooibos.storage.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,225 - DEBUG - Successfully registered viewer mediaplayer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,226 - DEBUG - Checking for viewers in rooibos.legacy.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,227 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,229 - DEBUG - Checking for viewers in rooibos.ui.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,230 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,232 - DEBUG - Checking for viewers in rooibos.viewers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,233 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,235 - DEBUG - Checking for viewers in rooibos.help.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,236 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,238 - DEBUG - Checking for viewers in rooibos.presentation.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,245 - DEBUG - Successfully registered viewer presentationviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,246 - DEBUG - Successfully registered viewer flashcardviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,247 - DEBUG - Successfully registered viewer printviewviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,248 - DEBUG - Successfully registered viewer packagefilesviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,249 - DEBUG - Successfully registered viewer htmlpresentation [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,250 - DEBUG - Checking for viewers in rooibos.statistics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,252 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,253 - DEBUG - Checking for viewers in rooibos.federatedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,255 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,256 - DEBUG - Checking for viewers in rooibos.unitedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,258 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,259 - DEBUG - Checking for viewers in rooibos.converters.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,261 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,262 - DEBUG - Checking for viewers in rooibos.contrib.tagging.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,264 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,265 - DEBUG - Checking for viewers in rooibos.workers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,267 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,268 - DEBUG - Checking for viewers in rooibos.userprofile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,270 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,271 - DEBUG - Checking for viewers in rooibos.mediaviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,273 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,274 - DEBUG - Checking for viewers in rooibos.megazine.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,277 - DEBUG - Successfully registered viewer megazine [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,278 - DEBUG - Checking for viewers in rooibos.groupmanager.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,279 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,281 - DEBUG - Checking for viewers in rooibos.pdfviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,283 - DEBUG - Successfully registered viewer pdfviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,284 - DEBUG - Checking for viewers in rooibos.pptexport.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,287 - DEBUG - Successfully registered viewer powerpointexportviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,288 - DEBUG - Checking for viewers in rooibos.audiotextsync.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,290 - DEBUG - Successfully registered viewer audiotextsyncviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:08,291 - DEBUG - Checking for viewers in pagination.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,292 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,293 - DEBUG - Checking for viewers in impersonate.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,295 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,296 - DEBUG - Checking for viewers in compressor.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,298 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,299 - DEBUG - Checking for viewers in south.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,301 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:08,302 - DEBUG - Checking for viewers in django_concurrent_test_server.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:08,304 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:09,769 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:33:09,766 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:33:09,772 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:33:10,029 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=%20[now-30days+to+*] HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:33:10,049 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:33:10,322 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:33:10,740 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=%20[now-30days+to+*]+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 83 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:33:17,059 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ecc2b10>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:33:20,886 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ecc2b10>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:33:34,669 - DEBUG - Checking for viewers in django.contrib.auth.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,672 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,673 - DEBUG - Checking for viewers in django.contrib.contenttypes.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,675 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,676 - DEBUG - Checking for viewers in django.contrib.sessions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,678 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,679 - DEBUG - Checking for viewers in django.contrib.sites.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,681 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,682 - DEBUG - Checking for viewers in django.contrib.flatpages.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,684 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,685 - DEBUG - Checking for viewers in django.contrib.admin.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,687 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,688 - DEBUG - Checking for viewers in django.contrib.humanize.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,690 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,691 - DEBUG - Checking for viewers in django.contrib.comments.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,693 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,694 - DEBUG - Checking for viewers in django.contrib.redirects.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,696 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,697 - DEBUG - Checking for viewers in django_extensions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,699 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,700 - DEBUG - Checking for viewers in google_analytics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,702 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,703 - DEBUG - Checking for viewers in rooibos.data.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,705 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,706 - DEBUG - Checking for viewers in rooibos.migration.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,708 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,709 - DEBUG - Checking for viewers in rooibos.mobile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,711 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,712 - DEBUG - Checking for viewers in rooibos.util.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,714 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,715 - DEBUG - Checking for viewers in rooibos.access.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,717 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,718 - DEBUG - Checking for viewers in rooibos.solr.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,720 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,721 - DEBUG - Checking for viewers in rooibos.storage.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,724 - DEBUG - Successfully registered viewer mediaplayer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,725 - DEBUG - Checking for viewers in rooibos.legacy.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,727 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,728 - DEBUG - Checking for viewers in rooibos.ui.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,730 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,731 - DEBUG - Checking for viewers in rooibos.viewers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,733 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,734 - DEBUG - Checking for viewers in rooibos.help.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,736 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,737 - DEBUG - Checking for viewers in rooibos.presentation.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,744 - DEBUG - Successfully registered viewer presentationviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,745 - DEBUG - Successfully registered viewer flashcardviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,746 - DEBUG - Successfully registered viewer printviewviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,747 - DEBUG - Successfully registered viewer packagefilesviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,748 - DEBUG - Successfully registered viewer htmlpresentation [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,749 - DEBUG - Checking for viewers in rooibos.statistics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,750 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,752 - DEBUG - Checking for viewers in rooibos.federatedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,753 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,755 - DEBUG - Checking for viewers in rooibos.unitedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,756 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,758 - DEBUG - Checking for viewers in rooibos.converters.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,759 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,761 - DEBUG - Checking for viewers in rooibos.contrib.tagging.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,762 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,764 - DEBUG - Checking for viewers in rooibos.workers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,765 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,767 - DEBUG - Checking for viewers in rooibos.userprofile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,768 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,770 - DEBUG - Checking for viewers in rooibos.mediaviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,771 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,773 - DEBUG - Checking for viewers in rooibos.megazine.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,775 - DEBUG - Successfully registered viewer megazine [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,776 - DEBUG - Checking for viewers in rooibos.groupmanager.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,778 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,779 - DEBUG - Checking for viewers in rooibos.pdfviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,782 - DEBUG - Successfully registered viewer pdfviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,783 - DEBUG - Checking for viewers in rooibos.pptexport.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,785 - DEBUG - Successfully registered viewer powerpointexportviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,786 - DEBUG - Checking for viewers in rooibos.audiotextsync.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,788 - DEBUG - Successfully registered viewer audiotextsyncviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:34,789 - DEBUG - Checking for viewers in pagination.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,791 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,792 - DEBUG - Checking for viewers in impersonate.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,794 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,795 - DEBUG - Checking for viewers in compressor.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,797 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,798 - DEBUG - Checking for viewers in south.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,800 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:34,801 - DEBUG - Checking for viewers in django_concurrent_test_server.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:34,803 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,878 - DEBUG - Checking for viewers in django.contrib.auth.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,880 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,882 - DEBUG - Checking for viewers in django.contrib.contenttypes.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,883 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,885 - DEBUG - Checking for viewers in django.contrib.sessions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,887 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,889 - DEBUG - Checking for viewers in django.contrib.sites.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,891 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,893 - DEBUG - Checking for viewers in django.contrib.flatpages.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,894 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,896 - DEBUG - Checking for viewers in django.contrib.admin.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,897 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,899 - DEBUG - Checking for viewers in django.contrib.humanize.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,901 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,903 - DEBUG - Checking for viewers in django.contrib.comments.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,904 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,906 - DEBUG - Checking for viewers in django.contrib.redirects.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,908 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,909 - DEBUG - Checking for viewers in django_extensions.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,911 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,912 - DEBUG - Checking for viewers in google_analytics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,914 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,916 - DEBUG - Checking for viewers in rooibos.data.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,917 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,919 - DEBUG - Checking for viewers in rooibos.migration.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,920 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,922 - DEBUG - Checking for viewers in rooibos.mobile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,924 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,925 - DEBUG - Checking for viewers in rooibos.util.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,927 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,929 - DEBUG - Checking for viewers in rooibos.access.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,930 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,932 - DEBUG - Checking for viewers in rooibos.solr.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,934 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,935 - DEBUG - Checking for viewers in rooibos.storage.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,939 - DEBUG - Successfully registered viewer mediaplayer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,940 - DEBUG - Checking for viewers in rooibos.legacy.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,942 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,943 - DEBUG - Checking for viewers in rooibos.ui.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,945 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,946 - DEBUG - Checking for viewers in rooibos.viewers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,948 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,949 - DEBUG - Checking for viewers in rooibos.help.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,951 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,952 - DEBUG - Checking for viewers in rooibos.presentation.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,960 - DEBUG - Successfully registered viewer presentationviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,961 - DEBUG - Successfully registered viewer flashcardviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,962 - DEBUG - Successfully registered viewer printviewviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,963 - DEBUG - Successfully registered viewer packagefilesviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,964 - DEBUG - Successfully registered viewer htmlpresentation [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,965 - DEBUG - Checking for viewers in rooibos.statistics.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,966 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,968 - DEBUG - Checking for viewers in rooibos.federatedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,969 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,971 - DEBUG - Checking for viewers in rooibos.unitedsearch.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,972 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,974 - DEBUG - Checking for viewers in rooibos.converters.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,975 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,977 - DEBUG - Checking for viewers in rooibos.contrib.tagging.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,978 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,980 - DEBUG - Checking for viewers in rooibos.workers.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,981 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,983 - DEBUG - Checking for viewers in rooibos.userprofile.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,984 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,986 - DEBUG - Checking for viewers in rooibos.mediaviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,987 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,989 - DEBUG - Checking for viewers in rooibos.megazine.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,992 - DEBUG - Successfully registered viewer megazine [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,993 - DEBUG - Checking for viewers in rooibos.groupmanager.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,994 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:47,996 - DEBUG - Checking for viewers in rooibos.pdfviewer.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:47,998 - DEBUG - Successfully registered viewer pdfviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:47,999 - DEBUG - Checking for viewers in rooibos.pptexport.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,002 - DEBUG - Successfully registered viewer powerpointexportviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:48,003 - DEBUG - Checking for viewers in rooibos.audiotextsync.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,005 - DEBUG - Successfully registered viewer audiotextsyncviewer [/opt/vic-did/rooibos/viewers/functions.py:register:79]
2015-07-14 11:33:48,006 - DEBUG - Checking for viewers in pagination.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,007 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:48,009 - DEBUG - Checking for viewers in impersonate.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,010 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:48,012 - DEBUG - Checking for viewers in compressor.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,013 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:48,015 - DEBUG - Checking for viewers in south.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,016 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:33:48,018 - DEBUG - Checking for viewers in django_concurrent_test_server.viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:60]
2015-07-14 11:33:48,019 - ERROR - Failed to import viewers: No module named viewers [/opt/vic-did/rooibos/viewers/functions.py:discover_viewers:65]
2015-07-14 11:34:26,146 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1e4bce90>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 11:34:26,333 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:34:26,329 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:34:26,341 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:34:26,413 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:34:26,671 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hats%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:34:26,707 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:34:26,954 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hats%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 877 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:34:37,103 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:34:37,139 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:34:37,739 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hats%20+&per_page=50&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 2155 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:35:37,212 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:35:37,213 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:35:37,220 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:35:37,422 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:35:37,478 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hats%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:35:37,498 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:35:38,220 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hats%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 879 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:35:57,685 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:35:57,681 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:35:57,689 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:35:57,804 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:35:57,958 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hats%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:35:57,978 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:35:58,213 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hats%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 879 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:36:14,326 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:36:14,323 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:36:14,337 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:36:14,628 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:36:14,647 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:36:14,829 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:36:15,693 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 879 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:36:29,798 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:36:29,813 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:36:29,801 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:36:29,911 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:36:30,041 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:36:30,046 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:36:30,439 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 880 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:37:06,415 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 11:37:06,418 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:37:06,430 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:37:06,627 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:37:06,661 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=hat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:37:06,666 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 11:37:06,952 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 880 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 11:37:13,057 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 11:37:13,094 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 11:37:13,556 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=hat%20+&per_page=50&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 2152 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 12:30:51,116 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea60c90>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:23:00,656 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ec4efd0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:23:02,142 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ebb49d0>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:23:02,493 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:23:02,490 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:23:02,497 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:02,733 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=outer%20space%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:23:02,752 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:23:03,574 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:04,248 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=outer%20space%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1030 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:23:06,155 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:23:06,158 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:06,167 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:23:06,348 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=outer%20space%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:23:06,353 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:23:07,033 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:07,625 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=outer%20space%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1029 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:23:09,719 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:23:09,723 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:09,731 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:23:09,946 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=space%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:23:09,951 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:23:10,387 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:23:11,043 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=space%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 977 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:33:09,121 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ecd2b90>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:33:10,168 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:33:10,169 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:33:10,175 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:33:10,371 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:33:10,418 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:33:10,439 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:33:10,779 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1194 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:33:38,250 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ecb9b50>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:43:06,520 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1ea8d550>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 13:43:11,512 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:43:11,510 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:43:11,517 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:11,763 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:11,784 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:43:12,451 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:13,036 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1153 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:18,317 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:43:18,321 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:18,330 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:43:18,535 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:18,540 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:43:18,978 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:19,774 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1153 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:24,502 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:43:25,282 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:25,924 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=50&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 2077 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:32,389 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:43:32,387 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:43:32,395 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:32,650 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:32,669 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:43:33,050 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:33,608 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1153 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:56,221 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:43:56,219 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:43:56,226 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:56,424 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:43:56,445 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:43:57,020 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:43:57,647 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1153 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:44:13,313 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:44:13,326 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:44:13,317 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:44:13,554 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:44:13,577 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:44:13,581 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:44:13,912 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1154 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:44:33,102 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:44:33,147 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:44:33,564 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=50&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 2078 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:45:24,212 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:45:24,404 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:45:24,845 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=50&page=2&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 2276 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:45:44,982 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 13:45:44,986 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:45:44,997 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 13:45:45,057 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 13:45:45,240 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cheese%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 13:45:45,251 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 13:45:45,451 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cheese%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 1149 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 15:56:17,459 - DEBUG - Defined impersonation signal (<django.dispatch.dispatcher.Signal object at 0x7fdd1eb75f50>) [/opt/vic-did/rooibos/contrib/impersonate/signals.py:<module>:6]
2015-07-14 15:56:18,405 - INFO - Starting new HTTP connection (1): 54.66.138.173 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:259]
2015-07-14 15:56:18,403 - INFO - Starting new HTTPS connection (1): api.flickr.com [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_new_conn:711]
2015-07-14 15:56:18,410 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 15:56:18,651 - DEBUG - "GET /ca14/service.php/find/ca_objects?q=cat%20 HTTP/1.1" 200 11 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
2015-07-14 15:56:18,672 - ERROR - Federated Search: 'results'
Traceback (most recent call last):
  File "/opt/vic-did/rooibos/federatedsearch/views.py", line 67, in run
    self.hits = self.instance.hits_count(query)
  File "/opt/vic-did/rooibos/unitedsearch/aggregate.py", line 23, in hits_count
    return searcher.count(keyword)
  File "/opt/vic-did/rooibos/unitedsearch/external/collectiveaccess.py", line 153, in count
    return len(search_object["results"])
KeyError: 'results'
 [/opt/vic-did/rooibos/federatedsearch/views.py:run:74]
2015-07-14 15:56:18,893 - DEBUG - Setting read timeout to None [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:390]
2015-07-14 15:56:19,341 - DEBUG - "GET /services/rest/?method=flickr.photos.search&api_key=3a092eb0151a289f86ea4b9bd71c3d8e&text=cat%20+&per_page=20&page=1&license=1%2C2%2C3%2C4%2C5%2C6&format=json&nojsoncallback=1 HTTP/1.1" 200 870 [/usr/lib/python2.7/dist-packages/urllib3/connectionpool.py:_make_request:430]
